apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: crx35ctx6-go 
  janus-idp.io/tekton: crx35ctx6-go
  backstage.io/kubernetes-id: crx35ctx6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: crx35ctx6-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  